### ISSUE TITLE
For some reason I cannot use generate in the archipelago launcher.  Console log in the description here

### ISSUE THREAD

**Issue by Septictank5** [DrBibop/Archipelago_Inscryption#2]
ERROR:root:Could not load world WorldSource(inscryption.apworld, is_zip=True, relative=True):
Traceback (most recent call last):
  File "worlds\__init__.py", line 70, in load
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProgramData\Archipelago\lib\worlds\inscryption.apworld\inscryption\__init__.py", line 1, in <module>
    from .Options import InscryptionOptions
  File "C:\ProgramData\Archipelago\lib\worlds\inscryption.apworld\inscryption\Options.py", line 3, in <module>
    from Options import Toggle, Choice, Option, PerGameCommonOptions
ImportError: cannot import name 'PerGameCommonOptions' from 'Options' (C:\ProgramData\Archipelago\lib\library.zip\Options.pyc)
Traceback (most recent call last):
  File "worlds\__init__.py", line 70, in load
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProgramData\Archipelago\lib\worlds\inscryption.apworld\inscryption\__init__.py", line 1, in <module>
    from .Options import InscryptionOptions
  File "C:\ProgramData\Archipelago\lib\worlds\inscryption.apworld\inscryption\Options.py", line 3, in <module>
    from Options import Toggle, Choice, Option, PerGameCommonOptions
ImportError: cannot import name 'PerGameCommonOptions' from 'Options' (C:\ProgramData\Archipelago\lib\library.zip\Options.pyc)
Archipelago (0.4.3) logging initialized on Windows-10-10.0.19045 running Python 3.11.5
P1 Weights: PlayerSettingsTemplate.yaml >> Template file from https://github.com/DrBibop/Archipelago_Inscryption/releases
Generating for 1 player, 98175895729647645505 Seed 79178719930777684597 with plando: bosses
Uncaught exception
Traceback (most recent call last):
  File "Generate.py", line 179, in main
  File "Generate.py", line 179, in <genexpr>
  File "Generate.py", line 455, in roll_settings
Exception: No world found to handle game Inscryption. Did you mean 'Minecraft' (36% sure)? Check your spelling or installation of that world.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__startup__.py", line 124, in run
  File "console.py", line 16, in run
  File "Generate.py", line 646, in <module>
  File "Generate.py", line 198, in main
ValueError: File PlayerSettingsTemplate.yaml is invalid. Please fix your yaml.
Traceback (most recent call last):
  File "Generate.py", line 179, in main
  File "Generate.py", line 179, in <genexpr>
  File "Generate.py", line 455, in roll_settings
Exception: No world found to handle game Inscryption. Did you mean 'Minecraft' (36% sure)? Check your spelling or installation of that world.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__startup__.py", line 124, in run
  File "console.py", line 16, in run
  File "Generate.py", line 646, in <module>
  File "Generate.py", line 198, in main
ValueError: File PlayerSettingsTemplate.yaml is invalid. Please fix your yaml.
Press enter to close.

**Comment by DrBibop** [comment]
Use v0.2.0, the previous version of releases. I switched to a newer options system that only works in the upcoming version of Archipelago (sry bout that, I didn't know). It should be able to generate if you use that version as long as you don't set your goal to Act 1 only.
